CREATE DATABASE IF NOT EXISTS vizag_florist CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE vizag_florist;

CREATE TABLE users (id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(120),email VARCHAR(190) UNIQUE,password_hash VARCHAR(255),phone VARCHAR(20),role ENUM('customer','vendor','admin') DEFAULT 'customer',status TINYINT DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE vendors (id BIGINT PRIMARY KEY AUTO_INCREMENT,user_id BIGINT,shop_name VARCHAR(160),commission_percent DECIMAL(5,2) DEFAULT 10.00,is_approved TINYINT DEFAULT 0,FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE categories (id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(120),slug VARCHAR(140) UNIQUE,parent_id BIGINT NULL,image_url VARCHAR(255),status TINYINT DEFAULT 1,FOREIGN KEY (parent_id) REFERENCES categories(id));
CREATE TABLE products (id BIGINT PRIMARY KEY AUTO_INCREMENT,vendor_id BIGINT,category_id BIGINT,name VARCHAR(180),slug VARCHAR(180) UNIQUE,description TEXT,price DECIMAL(10,2),image_url VARCHAR(255),stock INT DEFAULT 0,sold_count INT DEFAULT 0,is_featured TINYINT DEFAULT 0,status ENUM('active','inactive') DEFAULT 'active',FOREIGN KEY (vendor_id) REFERENCES vendors(id),FOREIGN KEY (category_id) REFERENCES categories(id));
CREATE TABLE product_addons (id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(120),price DECIMAL(10,2),type ENUM('checkbox','text') DEFAULT 'checkbox',status TINYINT DEFAULT 1);
CREATE TABLE product_addon_map (product_id BIGINT,addon_id BIGINT,PRIMARY KEY(product_id,addon_id),FOREIGN KEY (product_id) REFERENCES products(id),FOREIGN KEY (addon_id) REFERENCES product_addons(id));
CREATE TABLE cart_items (id BIGINT PRIMARY KEY AUTO_INCREMENT,user_id BIGINT,product_id BIGINT,qty INT DEFAULT 1,message_on_cake VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES users(id),FOREIGN KEY (product_id) REFERENCES products(id));
CREATE TABLE cart_item_addons (cart_item_id BIGINT,addon_id BIGINT,PRIMARY KEY(cart_item_id,addon_id),FOREIGN KEY (cart_item_id) REFERENCES cart_items(id),FOREIGN KEY (addon_id) REFERENCES product_addons(id));
CREATE TABLE delivery_slots (id BIGINT PRIMARY KEY AUTO_INCREMENT,title VARCHAR(120),start_time TIME,end_time TIME,charge DECIMAL(10,2) DEFAULT 0,status TINYINT DEFAULT 1);
CREATE TABLE coupons (id BIGINT PRIMARY KEY AUTO_INCREMENT,code VARCHAR(50) UNIQUE,discount_type ENUM('flat','percent'),discount_value DECIMAL(10,2),min_order_amount DECIMAL(10,2),max_discount DECIMAL(10,2),starts_at DATETIME,ends_at DATETIME,status TINYINT DEFAULT 1);
CREATE TABLE orders (id BIGINT PRIMARY KEY AUTO_INCREMENT,user_id BIGINT,subtotal DECIMAL(10,2),addon_total DECIMAL(10,2),delivery_charge DECIMAL(10,2),discount_amount DECIMAL(10,2),total_amount DECIMAL(10,2),payment_status ENUM('pending','paid','failed') DEFAULT 'pending',order_status ENUM('placed','confirmed','preparing','out_for_delivery','delivered','cancelled') DEFAULT 'placed',address_json JSON,delivery_date DATE,delivery_slot_id BIGINT,coupon_id BIGINT NULL,razorpay_order_id VARCHAR(120),razorpay_payment_id VARCHAR(120) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES users(id),FOREIGN KEY (delivery_slot_id) REFERENCES delivery_slots(id),FOREIGN KEY (coupon_id) REFERENCES coupons(id));
CREATE TABLE order_items (id BIGINT PRIMARY KEY AUTO_INCREMENT,order_id BIGINT,product_id BIGINT,vendor_id BIGINT,qty INT,unit_price DECIMAL(10,2),line_total DECIMAL(10,2),message_on_cake VARCHAR(255),FOREIGN KEY(order_id) REFERENCES orders(id),FOREIGN KEY(product_id) REFERENCES products(id),FOREIGN KEY(vendor_id) REFERENCES vendors(id));
CREATE TABLE order_item_addons (id BIGINT PRIMARY KEY AUTO_INCREMENT,order_item_id BIGINT,addon_id BIGINT,addon_name VARCHAR(120),addon_price DECIMAL(10,2),FOREIGN KEY(order_item_id) REFERENCES order_items(id),FOREIGN KEY(addon_id) REFERENCES product_addons(id));
CREATE TABLE banners (id BIGINT PRIMARY KEY AUTO_INCREMENT,title VARCHAR(120),image_url VARCHAR(255),link_url VARCHAR(255),sort_order INT DEFAULT 0,status TINYINT DEFAULT 1);
CREATE TABLE cms_pages (id BIGINT PRIMARY KEY AUTO_INCREMENT,slug VARCHAR(80) UNIQUE,title VARCHAR(160),content LONGTEXT,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE payouts (id BIGINT PRIMARY KEY AUTO_INCREMENT,vendor_id BIGINT,order_item_id BIGINT,gross_amount DECIMAL(10,2),commission_amount DECIMAL(10,2),net_amount DECIMAL(10,2),payout_status ENUM('pending','processed') DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(vendor_id) REFERENCES vendors(id),FOREIGN KEY(order_item_id) REFERENCES order_items(id));
